name: CLXGeyserBandaid
version: '1.0-SNAPSHOT'
main: gg.corn.CLXGeyserBandaid.CLXGeyserBandaid
api-version: '1.21'
depend:
  - CombatLogX
  - Floodgate
  - Paper
description: Blocks elytra flight for Bedrock players connected through Floodgate.